[tool.poetry]
name = "mantarix-cli"
version = "0.1.0"
description = "Mantarix CLI"
authors = ["Appveyor Systems Inc. <hello@mantarix.dev>"]
license = "Apache-2.0"

packages = [{ include = "mantarix_cli", from = "src" }]

[tool.poetry.urls]
repository = "https://github.com/mantarix-dev/mantarix"

[tool.poetry.dependencies]
python = "^3.8"
mantarix = { version = "0.1.0" }
watchdog = "^4.0.0"
packaging = "*"
qrcode = "^7.4.2"
toml = "^0.10.2"
cookiecutter = "^2.6.0"

[tool.poetry.plugins."pyinstaller40"]
hook-dirs = "mantarix_cli.__pyinstaller:get_hook_dirs"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true
