[tool.poetry]
name = "mantarix"
version = "0.1.0"
description = "mantarix for Python - easily build interactive multi-platform apps in Python"
authors = ["Mantarix Systems Inc. <hello@mantarix.dev>"]
license = "Apache-2.0"

packages = [{ include = "mantarix", from = "src" }]

[tool.poetry.urls]
repository = "https://github.com/mantarix-dev/mantarix"

[tool.poetry.dependencies]
python = "^3.8"
mantarix-cli = { version = "0.1.0", optional = true }
mantarix-desktop = { version = "0.1.0", optional = true, markers = "platform_system == 'Darwin' or platform_system == 'Windows'" }
mantarix-web = { version = "0.1.0", optional = true }
oauthlib = { version = "^3.2.2", markers = "platform_system != 'Pyodide'" }
httpx = { version = "*", markers = "platform_system != 'Pyodide'" }
repath = "^0.9.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.6"
pytest = "^7.2.0"
cryptography = "^39.0.0"

[tool.poetry.extras]
all = ["mantarix-cli", "mantarix-desktop", "mantarix-web"]
cli = ["mantarix-cli"]
web = ["mantarix-web"]
desktop = ["mantarix-desktop"]

[tool.poetry.scripts]
mantarix = "mantarix.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"