[tool.poetry]
name = "mantarix-desktop"
version = "0.1.0"
description = "Mantarix Desktop client in Flutter"
authors = ["Mantarix Systems Inc. <hello@mantarix.dev>"]
license = "Apache-2.0"

packages = [
    { include = "mantarix_desktop", from = "src" },
]

include = [
    { path = "src/mantarix_desktop/app/**/*", format = ["sdist", "wheel"] },
]

[tool.poetry.urls]
repository = "https://github.com/mantarix-dev/mantarix"

[tool.poetry.dependencies]
python = "^3.8"
mantarix = { version = "0.1.0" }

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.6"
pytest = "^7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
float_to_top = true
